Database: C:/Users/Moni/CLionProjects/Database/sources/Table.cpp File Reference
Table.cpp File Reference
#include <fstream>
#include <sstream>
#include <iostream>
#include "../headers/Table.h"
#include <algorithm>
Functions
std::ostream & operator<< (std::ostream &out, const Table &table)
bool isInteger (const std::string &input)
checks if a given string is an integer
bool isDouble (const std::string &input)
checks if a given string is a double
Function Documentation
isDouble()
bool isDouble (const std::string & input)
checks if a given string is a double
Definition at line 249 of file Table.cpp.
{
     int dotsCount =0;
     if(input.empty()){
         return false;
     }
     for(int i=0;i<input.size();i++){
         char c = input.at(i);
         if(i==0 && (c == '+' || c == '-') && input.size()==1){
             return false;
         }
         else if(i==0 && (c == '+' || c == '-')){
             continue;
         }
         else if(!isdigit(c) && c=='.'){
             dotsCount++;
             continue;
         }
         else if(!isdigit(c)){
             return false;
         }
     }
     return  dotsCount == 1;
 }
isInteger()
bool isInteger (const std::string & input)
checks if a given string is an integer
Definition at line 230 of file Table.cpp.
{
    if(input.empty()){
        return false;
    }
    for(int i=0;i<input.size();i++){
        char c = input.at(i);
        if(i==0 && (c == '+' || c == '-') && input.size()==1){
            return false;
        }
        else if(i==0 && (c == '+' || c == '-')){
            continue;
        }
        if(!isdigit(c)){
            return false;
        }
    }
    return true;
 }
operator<<()
std::ostream& operator<< (std::ostream & out, const Table & table)
Definition at line 103 of file Table.cpp.
{
     out<<table.getTableName()+',';
     for(int i=0;i<table.getTypes().size()-1;i++){
         out<<table.getTypes()[i]+',';
     }
     out<<table.getTypes()[table.getTypes().size()-1]<<std::endl;
     for(int i=0;i<table.getColNames().size()-1;i++){
         out<<table.getColNames()[i]+',';
     }
     out<<table.getColNames()[table.getColNames().size()-1]<<std::endl;
     for(int i=0;i<table.getRows().size();i++){
         out<<table.getRows()[i]<<std::endl;
     }
     return out;
 }
References Table::getColNames(), Table::getRows(), Table::getTableName(), and Table::getTypes().