Database: Catalog Class Reference
Catalog Class Reference
Клас който дефинира каталог (списък от таблици и имена на таблици)
#include <Catalog.h>
Public Member Functions
Catalog ()
const std::map< std::string, std::string > & getCatalog () const
void setCatalog (const std::map< std::string, std::string > &catalog)
void insertTableInCatalog (const std::string &name, const std::string &path)
adds a table in the catalog if it doesn't exists in the catalog
Table getTableByName (const std::string &name)
return a table by given table name if it exists
bool tableExistsInCatalog (const std::string &tableName)
checks if a given table name exists in the catalog
void changeTableName (const std::string &oldName, const std::string &newName)
changes a table name by given old table name and new table name
Private Attributes
std::map< std::string, std::string > catalog
Friends
std::ostream & operator<< (std::ostream &out, Catalog &object)
std::istream & operator>> (std::istream &in, Catalog &object)
Detailed Description
Клас който дефинира каталог (списък от таблици и имена на таблици)
Definition at line 16 of file Catalog.h.
Constructor & Destructor Documentation
Catalog()
Catalog::Catalog ()
Definition at line 31 of file Catalog.cpp.
                  {
 }
Member Function Documentation
changeTableName()
void Catalog::changeTableName (const std::string & oldName, const std::string & newName)
changes a table name by given old table name and new table name
Definition at line 64 of file Catalog.cpp.
{
     std::map<std::string, std::string>::iterator it = this->catalog.find(oldName);
     if (it == this->catalog.end()) {
         throw std::invalid_argument("Table not found!");
     }
     std::string path = this->getTableByName(oldName).getPathToFile();
     this->catalog.erase(oldName);
     this->insertTableInCatalog(newName, path);
 }
References catalog, Table::getPathToFile(), getTableByName(), insertTableInCatalog(), and string.
getCatalog()
const std::map< std::string, std::string > & Catalog::getCatalog () const
Definition at line 23 of file Catalog.cpp.
{
     return catalog;
 }
References catalog.
getTableByName()
Table Catalog::getTableByName (const std::string & name)
return a table by given table name if it exists
Definition at line 45 of file Catalog.cpp.
{
     //check if exists
     if (this->catalog.find(name) == this->catalog.end()) {
         throw std::invalid_argument("received invalid name of table");
     } else {
         return this->catalog.at(name);
     }
 }
References catalog.
insertTableInCatalog()
void Catalog::insertTableInCatalog (const std::string & name, const std::string & path)
adds a table in the catalog if it doesn't exists in the catalog
Definition at line 35 of file Catalog.cpp.
{
     std::map<std::string, std::string>::iterator it = this->catalog.find(name);
     if (it != this->catalog.end()) {
         throw std::invalid_argument("Table already exists");
     }
     this->catalog.insert(std::make_pair(name, path));
 }
References catalog, and name.
setCatalog()
void Catalog::setCatalog (const std::map< std::string, std::string > & catalog)
Definition at line 27 of file Catalog.cpp.
{
     Catalog::catalog = catalog;
 }
References catalog.
tableExistsInCatalog()
bool Catalog::tableExistsInCatalog (const std::string & tableName)
checks if a given table name exists in the catalog
Definition at line 55 of file Catalog.cpp.
{
     try {
         getTableByName(tableName);
         return true;
     } catch (const std::invalid_argument &e) {
         return false;
     }
 }
References getTableByName().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, Catalog & object) friend
Definition at line 10 of file Catalog.cpp.
{
     std::map<std::string, std::string>::iterator it;
     for (auto const &x : object.catalog) {
         out << (x.first + " - " + x.second) << '\n';
     }
     return out;
 }
operator>>
std::istream& operator>> (std::istream & in, Catalog & object) friend
Definition at line 18 of file Catalog.cpp.
{
     return in;
 }
Member Data Documentation
catalog
std::map<std::string, std::string> Catalog::catalog private
Definition at line 18 of file Catalog.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Database/headers/Catalog.h
C:/Users/Moni/CLionProjects/Database/sources/Catalog.cpp