Database: Table Class Reference
Table Class Reference
Клас който дефинира таблица
#include <Table.h>
Public Member Functions
Table ()
Table (const std::string &pathToFile)
const std::string & getTableName () const
void setTableName (const std::string &tableName)
const std::vector< std::string > & getTypes () const
void setTypes (const std::vector< std::string > &types)
const std::vector< std::string > & getRows () const
void setRows (const std::vector< std::string > &rows)
const std::string & getPathToFile () const
void setPathToFile (const std::string &pathToFile)
std::vector< std::string > splitLineByDelimeter (char delimeter, std::string line)
splits a string into tokens by given delimeter
void insertRow (const std::string &row)
std::string removeNewLines (const std::string &line)
removes the new lines symbols by given line
void printSelectColByVal (int col, const std::string &value)
prints col by given col and value
void deleteRowsByColValue (int col, const std::string &value)
delete rows by given col and val
void saveTableToCurrentFile ()
saves the table to the current file
void updateTableVal (int searchCol, const std::string &searchVal, int targetColconst, const std::string &value)
updates table values by given search col, search value, target col and the value we want
void insertRowInTable (const std::string &columns)
inswers a row into the table
void addRowInRows (const std::string &row)
adds a row into the table by given string
void addColInCols (const std::string &colName)
adds a col in the table by given name
void addTypeToTypes (const std::string &type)
add the type to the end of types
void changeName (const std::string &newName)
changes the name of the table by given new name string
void insertColInTable (const std::string &colName, const std::string &colType)
inserts a col in the table by given name and type
const std::vector< std::string > & getColNames () const
void setColNames (const std::vector< std::string > &colNames)
void addNullToTheEndOfEveryRow ()
adds a NULL value to the end of all rows
void addValToTheEndOfRow (int id, const std::string &value)
adds a value to the end of row
void getCountOfValInCol (int index, const std::string &value)
Prints the number of occurences on given col index and value.
void printRows ()
Print rows on the table.
void printFromStartIndexToEndIndex (int startIndex, int endIndex, const std::vector< std::string > &rows)
prints rows by given start index, end index and rows
void aggregateOperations (int searchCol, const std::string &searchVal, int targetCol, const std::string &operation)
aggregate function by given search col, search val,
void printTypesByDelimeter (char del)
prints types by given delimeter char
void printColNamesByDelimeter (char del)
prints col names by given delimeter char
std::string innerJoin (int col, const Table &joinTable, int targetCol)
inner joins two tables based on given col index, table name and target col
Private Attributes
std::string pathToFile
std::string tableName
std::vector< std::string > types
std::vector< std::string > rows
std::vector< std::string > colNames
Friends
std::ostream & operator<< (std::ostream &out, const Table &object)
std::istream & operator>> (std::istream &in, Table &object)
Detailed Description
Клас който дефинира таблица
Definition at line 16 of file Table.h.
Constructor & Destructor Documentation
Table() [1/2]
Table::Table ()
Definition at line 11 of file Table.cpp.
              {
 }
Table() [2/2]
Table::Table (const std::string & pathToFile)
Definition at line 15 of file Table.cpp.
{
     setPathToFile(pathToFile);
     std::string line;
     std::ifstream myfile (pathToFile);
     if (myfile.is_open())
     {
         getline (myfile,line);
         std::vector<std::string> tokens = splitLineByDelimeter(',',line);
         setTableName(tokens[0]);
         tokens.erase(tokens.begin(),tokens.begin()+1);
         setTypes(tokens);
         getline (myfile,line);
         std::vector<std::string> colNames = splitLineByDelimeter(',',line);
         this->setColNames(colNames);
         while ( getline (myfile,line) )
         {
             std::string formattedLine = removeNewLines(line);
             this->insertRow(formattedLine);
         }
         myfile.close();
     }
     else std::cout << "Unable to open file";
 }
References colNames, insertRow(), pathToFile, removeNewLines(), setColNames(), setPathToFile(), setTableName(), setTypes(), splitLineByDelimeter(), and string.
Member Function Documentation
addColInCols()
void Table::addColInCols (const std::string & colName)
adds a col in the table by given name
Definition at line 425 of file Table.cpp.
{
     std::vector<std::string> colNames = this->getColNames();
     for(int i=0;i<colNames.size();i++){
         std::string colNameTemp = colNames[i];
         if(colNameTemp == colName){
             throw std::invalid_argument( "col with this name already exists" );
         }
     }
     this->colNames.push_back(colName);
 }
References colNames, getColNames(), and string.
addNullToTheEndOfEveryRow()
void Table::addNullToTheEndOfEveryRow ()
adds a NULL value to the end of all rows
Definition at line 419 of file Table.cpp.
{
     for(int i=0;i<this->getRows().size();i++){
         addValToTheEndOfRow(i,"NULL");
     }
 }
References addValToTheEndOfRow(), and getRows().
addRowInRows()
void Table::addRowInRows (const std::string & row)
adds a row into the table by given string
Definition at line 403 of file Table.cpp.
{
     this->rows.push_back(row);
 }
References rows.
addTypeToTypes()
void Table::addTypeToTypes (const std::string & type)
add the type to the end of types
Definition at line 445 of file Table.cpp.
{
     if(type != "string"
        && type != "int"
        && type != "double" ){
         throw std::invalid_argument( "received invalid col type" );
     }
     this->types.push_back(type);
 }
References types.
addValToTheEndOfRow()
void Table::addValToTheEndOfRow (int id, const std::string & value)
adds a value to the end of row
Definition at line 454 of file Table.cpp.
{
     if(id<0 || id>this->getRows().size()){
         throw std::invalid_argument( "received invalid row" );
     }
     this->rows[id] += ","+value;
 }
References getRows(), id, and rows.
aggregateOperations()
void Table::aggregateOperations (int searchCol, const std::string & searchVal, int targetCol, const std::string & operation)
aggregate function by given search col, search val,
Definition at line 544 of file Table.cpp.
{
     if(searchCol< 0
             || searchCol>this->getTypes().size()
             || targetCol< 0
             || targetCol>this->getTypes().size()){
         throw std::invalid_argument( "received invalid index" );
     }
     searchCol--;
     targetCol--;
     if((this->getTypes()[searchCol] != "double" && this->getTypes()[searchCol] != "int")
     ||(this->getTypes()[targetCol] != "double" && this->getTypes()[targetCol] != "int") ){
         throw std::invalid_argument( "received invalid index of col" );
     }
     std::vector<std::string> targetRowsValues;
     for(int i=0;i<this->getRows().size();i++){
         std::string row = this->getRows()[i];
         std::vector<std::string> tokens = splitLineByDelimeter(',',row);
         std::string valueToCheck = tokens.at(searchCol);
         if(searchVal == valueToCheck ){
             if(tokens[targetCol] != "NULL")
                 targetRowsValues.push_back(tokens[targetCol]);
         }
     }
     if(operation=="sum"){
         double sum = 0;
         for(int i=0;i<targetRowsValues.size();i++){
             if(targetRowsValues[i] !="NULL"){
             double currentVal = std::stod(targetRowsValues[i]);
             sum += currentVal;
             }
         }
         std::cout<<"Sum: "<<sum<<std::endl;
     }
     else if(operation=="maximum"){
         double max = std::numeric_limits<double>::lowest();
         for(int i=0;i<targetRowsValues.size();i++){
             if(targetRowsValues[i] !="NULL") {
                 double currentVal = std::stod(targetRowsValues[i]);
                 if (currentVal > max) {
                     max = currentVal;
                 }
             }
         }
         std::cout<<"Max: "<<max<<std::endl;
     }
     else if(operation=="minimum"){
         double min = std::numeric_limits<double>::max();
         for(int i=0;i<targetRowsValues.size();i++){
             if(targetRowsValues[i] !="NULL") {
                 double currentVal = std::stod(targetRowsValues[i]);
                 if (currentVal < min) {
                     min = currentVal;
                 }
             }
         }
         std::cout<<"Min: "<<min<<std::endl;
     }
     else if(operation=="product"){
         double product = 1;
         for(int i=0;i<targetRowsValues.size();i++){
             if(targetRowsValues[i] !="NULL") {
                 double currentVal = std::stod(targetRowsValues[i]);
                 product *= currentVal;
             }
         }
         std::cout<<"Product: "<<product<<std::endl;
     }
 }
References getRows(), getTypes(), splitLineByDelimeter(), and string.
changeName()
void Table::changeName (const std::string & newName)
changes the name of the table by given new name string
Definition at line 408 of file Table.cpp.
{
     this->setTableName(newName);
 }
References setTableName().
deleteRowsByColValue()
void Table::deleteRowsByColValue (int col, const std::string & value)
delete rows by given col and val
Definition at line 174 of file Table.cpp.
{
     std::vector<std::string> newTableRows;
     if(col> this->getTypes().size() || col<0){
         std::cout<<"Col out of bound"<<std::endl;
         return;
     }
     std::string type = this->getTypes().at(col-1);
     for(int i=0;i<this->getRows().size();i++){
         std::string row = this->getRows()[i];
         std::vector<std::string> tokens = this->splitLineByDelimeter(',',row);
         std::string valToCheck = tokens.at(col-1);
         if((valToCheck == "NULL" && value != "NULL")
            ||  (valToCheck != "NULL" && value == "NULL")){
             newTableRows.push_back(row);
             continue;
         }
         if(valToCheck == "NULL" && value == "NULL"){
             continue;
         }
         if(type == "int"){
             int toCheck = std::stoi(valToCheck);
             int valueChecked = std::stoi(value);
             if(toCheck != valueChecked){
                 newTableRows.push_back(row);
             }
         }
         else if(type=="string"){
             if(value != valToCheck){
                 newTableRows.push_back(row);
             }
         }
         else if(type=="double"){
             double toCheck = std::stod(valToCheck);
             double valueChecked = std::stod(value);
             if(toCheck != valueChecked){
                 newTableRows.push_back(row);
             }
         }
     }
     this->setRows(newTableRows);
 }
References getRows(), getTypes(), setRows(), splitLineByDelimeter(), and string.
getColNames()
const std::vector< std::string > & Table::getColNames () const
Definition at line 437 of file Table.cpp.
{
     return colNames;
 }
References colNames.
getCountOfValInCol()
void Table::getCountOfValInCol (int index, const std::string & value)
Prints the number of occurences on given col index and value.
Definition at line 464 of file Table.cpp.
{
     if(index<0 || index>this->getTypes().size()){
         throw std::invalid_argument( "received invalid index" );
     }
     int counter = 0;
     for(int i=0;i< this->getRows().size();i++){
         std::string row = this->getRows()[i];
         std::vector<std::string> tokens = splitLineByDelimeter(',',row);
         std::string valueToBeChecked = tokens[index-1];
         if(valueToBeChecked == value)
           counter++;
     }
     std::cout<<"Number of occurrences: "<<counter<<std::endl;
 }
References getRows(), getTypes(), splitLineByDelimeter(), and string.
getPathToFile()
const std::string & Table::getPathToFile () const
Definition at line 78 of file Table.cpp.
{
     return pathToFile;
 }
References pathToFile.
getRows()
const std::vector< std::string > & Table::getRows () const
Definition at line 70 of file Table.cpp.
{
     return rows;
 }
References rows.
getTableName()
const std::string & Table::getTableName () const
Definition at line 54 of file Table.cpp.
{
     return tableName;
 }
References tableName.
getTypes()
const std::vector< std::string > & Table::getTypes () const
Definition at line 62 of file Table.cpp.
{
     return types;
 }
References types.
innerJoin()
std::string Table::innerJoin (int col, const Table & joinTable, int targetCol)
inner joins two tables based on given col index, table name and target col
Definition at line 634 of file Table.cpp.
{
     if(col<0 || col>this->getTypes().size() ||
             targetCol<0 || targetCol>joinTable.getTypes().size() ){
         throw std::invalid_argument( "received invalid index of col" );
     }
     std::string firstTableColType = this->getTypes().at(col-1);
     std::string secondTableColType = joinTable.getTypes().at(targetCol-1);
     if(firstTableColType!=secondTableColType){
         throw std::invalid_argument( "Can't join tables with two different field types!" );
     }
     std::string newJoinedTableName = this->getTableName()
             + "_JOIN_"+joinTable.getTableName()+"_COL_"
             +std::to_string(col)+"_AND_"+std::to_string(targetCol);
     Table newTable = Table();
     newTable.setTableName(newJoinedTableName);
     std::vector<std::string> types;
     for(int i=0;i<this->getTypes().size();i++){
         types.push_back(this->getTypes()[i]);
     }
     for(int i=0;i<joinTable.getTypes().size();i++){
         types.push_back(joinTable.getTypes()[i]);
     }
     newTable.setTypes(types);
     std::vector<std::string> colNames;
     for(int i=0;i<this->getColNames().size();i++){
         colNames.push_back(this->getColNames()[i]);
     }
     for(int i=0;i<joinTable.getColNames().size();i++){
         colNames.push_back(joinTable.getColNames()[i]);
     }
     newTable.setColNames(colNames);
     newTable.setPathToFile("..//tables//"+newJoinedTableName+".txt");
     std::vector<std::string> newTableRows;
     for(int i=0;i<this->getRows().size();i++){
         std::string currentRow = this->getRows()[i];
         std::vector<std::string> tokens = splitLineByDelimeter(',',currentRow);
         std::string currentValOnRow = tokens.at(col-1);
         for(int j =0;j<joinTable.getRows().size();j++){
             std::string joinedCurrentRow = joinTable.getRows()[j];
             std::vector<std::string> joinedTokens = splitLineByDelimeter(',',joinedCurrentRow);
             std::string joinedCurrentValOnRow = joinedTokens.at(targetCol-1);
             if(joinedCurrentValOnRow == currentValOnRow ){
                 //same target col
                 std::string rowToAdd = currentRow+","+joinedCurrentRow;
                 newTableRows.push_back(rowToAdd);
             }
         }
     }
     newTable.setRows(newTableRows);
     newTable.saveTableToCurrentFile();
     std::cout<<newTable.getTableName()<<std::endl;
     return newTable.getPathToFile();
 }
References colNames, getColNames(), getPathToFile(), getRows(), getTableName(), getTypes(), saveTableToCurrentFile(), setColNames(), setPathToFile(), setRows(), setTableName(), setTypes(), splitLineByDelimeter(), string, Table(), and types.
insertColInTable()
void Table::insertColInTable (const std::string & colName, const std::string & colType)
inserts a col in the table by given name and type
Definition at line 412 of file Table.cpp.
{
     addColInCols(colName);
     addTypeToTypes(colType);
     addNullToTheEndOfEveryRow();
 }
References addColInCols(), addNullToTheEndOfEveryRow(), and addTypeToTypes().
insertRow()
void Table::insertRow (const std::string & row)
Definition at line 86 of file Table.cpp.
{
     this->rows.push_back(row);
 }
References rows.
insertRowInTable()
void Table::insertRowInTable (const std::string & columns)
inswers a row into the table
Definition at line 367 of file Table.cpp.
{
     std::vector<std::string> tokens = this->splitLineByDelimeter(' ',columns);
     std::string row = "";
     bool invalid = false;
     for(int i=0;i<tokens.size();i++){
         if(invalid){
             break;
         }
         std::string type = this->getTypes()[i];
         std::string currentValFromCol = tokens[i];
         if(type=="double"){
             if(!isDouble(currentValFromCol)){
                 std::cout<<"Invalid format for col"<<std::endl;
                 invalid = true;
             }
         }else if(type == "int"){
             if(!isInteger(currentValFromCol)){
                 std::cout<<"Invalid format for col"<<std::endl;
                 invalid = true;
             }
         }
     }
     if(invalid){
         return;
     }
     for(int i=0;i<tokens.size()-1;i++){
         row += tokens[i]+",";
     }
     row+=tokens[tokens.size()-1];
     this->addRowInRows(row);
     std::cout<<"Successfully added row:"<<row<<"!"<<std::endl;
 }
References addRowInRows(), getTypes(), invalid, isDouble(), isInteger(), splitLineByDelimeter(), and string.
printColNamesByDelimeter()
void Table::printColNamesByDelimeter (char del)
prints col names by given delimeter char
Definition at line 626 of file Table.cpp.
{
     for(int i=0;i<this->getColNames().size()-1;i++){
         std::cout<<this->getColNames()[i]<<del;
     }
     std::cout<<this->getColNames()[this->getColNames().size()-1]<<std::endl;
 }
References getColNames().
printFromStartIndexToEndIndex()
void Table::printFromStartIndexToEndIndex (int startIndex, int endIndex, const std::vector< std::string > & rows)
prints rows by given start index, end index and rows
Definition at line 526 of file Table.cpp.
{
     if(startIndex<0){
         return;
     }
     std::cout<<"Types: ";
     printTypesByDelimeter(',');
     std::cout<<"Col names: ";
     printColNamesByDelimeter(',');
     int counter =0;
     for(int index = startIndex,i=1; index<endIndex && index<rows.size();index++,i++){
         std::cout<<i<<": "<<rows.at(index)<<std::endl;
         counter++;
     }
     std::cout<<"Showing from: "<<startIndex+1<<" to "<<startIndex+counter<<"! All: "<<rows.size()<<std::endl;
 }
References printColNamesByDelimeter(), printTypesByDelimeter(), and rows.
printRows()
void Table::printRows ()
Print rows on the table.
Definition at line 481 of file Table.cpp.
                       {
     int numberOfRowsOnOnePage = 10;
     int startIndex =0;
     int endIndex = startIndex+numberOfRowsOnOnePage;
     std::vector<std::string> rows = getRows();
     std::string command;
     printFromStartIndexToEndIndex(0,endIndex,rows);
     std::cout<<"Available commands: next, previous and exit!"<<std::endl;
     getline(std::cin, command);
     while (true){
         if(command == "exit"){
             std::cout<<"Successfully exited print command"<<std::endl;
             break;
         }
         else if(command=="next"){
             if(startIndex+numberOfRowsOnOnePage < rows.size()){
                 endIndex += numberOfRowsOnOnePage;
                 startIndex += numberOfRowsOnOnePage;
             }else{
                 std::cout<<"out of bound"<<std::endl;
                 getline(std::cin, command);
                 continue;
             }
         }else if(command=="previous"){
             if(startIndex - numberOfRowsOnOnePage>=0){
                 startIndex -= numberOfRowsOnOnePage;
                 endIndex -= numberOfRowsOnOnePage;
             } else{
                 std::cout<<"out of bound"<<std::endl;
                 getline(std::cin, command);
                 continue;
             }
         }
         printFromStartIndexToEndIndex(startIndex,endIndex,rows);
         std::cout<<"Available commands: next, previous and exit!"<<std::endl;
         getline(std::cin, command);
     }
 }
References getRows(), printFromStartIndexToEndIndex(), rows, and string.
printSelectColByVal()
void Table::printSelectColByVal (int col, const std::string & value)
prints col by given col and value
Definition at line 123 of file Table.cpp.
{
     if(col> this->getTypes().size() || col<0){
         std::cout<<"Col out of bound"<<std::endl;
         return;
     }
     std::string type = this->getTypes().at(col-1);
     std::vector<std::string> rowsContainingValue;
     for(int i=0;i<this->getRows().size();i++){
         std::string row = this->getRows()[i];
         std::vector<std::string> tokens = this->splitLineByDelimeter(',',row);
         std::string valToCheck = tokens.at(col-1);
         if((valToCheck == "NULL" && value != "NULL")
             ||  (valToCheck != "NULL" && value == "NULL")){
             continue;
         }
         if(valToCheck == "NULL" && value == "NULL"){
             rowsContainingValue.push_back(row);
             continue;
         }
         if(type == "int"){
             int toCheck = std::stoi(valToCheck);
             int valueChecked = std::stoi(value);
             if(toCheck == valueChecked){
                 rowsContainingValue.push_back(row);
             }
         }
         else if(type=="string"){
             if(value == valToCheck){
                 rowsContainingValue.push_back(row);
             }
         }
         else if(type=="double"){
             double toCheck = std::stod(valToCheck);
             double valueChecked = std::stod(value);
             if(toCheck == valueChecked){
                 rowsContainingValue.push_back(row);
             }
         }
     }
     if(rowsContainingValue.empty()){
         std::cout<<"0 matching values found"<<std::endl;
     }
     for(int i=0;i<rowsContainingValue.size();i++){
         std::cout<<rowsContainingValue[i]<<std::endl;
     }
 }
References getRows(), getTypes(), splitLineByDelimeter(), and string.
printTypesByDelimeter()
void Table::printTypesByDelimeter (char del)
prints types by given delimeter char
Definition at line 618 of file Table.cpp.
{
     for(int i=0;i<this->getTypes().size()-1;i++){
         std::cout<<this->getTypes()[i]<<del;
     }
     std::cout<<this->getTypes()[this->getTypes().size()-1]<<std::endl;
 }
References getTypes().
removeNewLines()
std::string Table::removeNewLines (const std::string & line)
removes the new lines symbols by given line
Definition at line 90 of file Table.cpp.
{
     std::string lineToChange = line;
     while ( line.find ("\r") != std::string::npos )
     {
         lineToChange.erase ( line.find ("\r"), 2 );
     }
     while ( line.find ("\n") != std::string::npos )
     {
         lineToChange.erase ( line.find ("\n"), 2 );
     }
     return lineToChange;
 }
References string.
saveTableToCurrentFile()
void Table::saveTableToCurrentFile ()
saves the table to the current file
Definition at line 221 of file Table.cpp.
{
     std::ofstream myfile (this->getPathToFile());
     if (myfile.is_open())
     {
         myfile << *this;
         myfile.close();
     }
 }
References getPathToFile().
setColNames()
void Table::setColNames (const std::vector< std::string > & colNames)
Definition at line 441 of file Table.cpp.
{
     Table::colNames = colNames;
 }
References colNames.
setPathToFile()
void Table::setPathToFile (const std::string & pathToFile)
Definition at line 82 of file Table.cpp.
{
     Table::pathToFile = pathToFile;
 }
References pathToFile.
setRows()
void Table::setRows (const std::vector< std::string > & rows)
Definition at line 74 of file Table.cpp.
{
     Table::rows = rows;
 }
References rows.
setTableName()
void Table::setTableName (const std::string & tableName)
Definition at line 58 of file Table.cpp.
{
     Table::tableName = tableName;
 }
References tableName.
setTypes()
void Table::setTypes (const std::vector< std::string > & types)
Definition at line 66 of file Table.cpp.
{
     Table::types = types;
 }
References types.
splitLineByDelimeter()
std::vector< std::string > Table::splitLineByDelimeter (char delimeter, std::string line)
splits a string into tokens by given delimeter
Definition at line 41 of file Table.cpp.
{
     line = removeNewLines(line);
     std::stringstream steam(line);
     std::string splited;
     std::vector<std::string> tokens;
     while(getline(steam, splited, delimeter))
     {
         tokens.push_back(splited);
     }
     return tokens;
 }
References removeNewLines(), and string.
updateTableVal()
void Table::updateTableVal (int searchCol, const std::string & searchVal, int targetColconst, const std::string & value)
updates table values by given search col, search value, target col and the value we want
Definition at line 274 of file Table.cpp.
{
     //check if index out of bound
     if(searchCol> this->getTypes().size() || searchCol<0
         ||targetCol> this->getTypes().size() || targetCol<0){
         std::cout<<"Col out of bound"<<std::endl;
         return;
     }
     std::string type = this->getTypes().at(searchCol-1);
     std::vector<std::string> newTableRows;
     std::string targetColType = this->getTypes().at(targetCol-1);
     if(valueToChange == "NULL"){
         //do nothing,because null is valid new value
     }else if(targetColType == "int"){
         if(!isInteger(valueToChange)){
             std::cout<<"Invalid new update value. It should be:"<<targetColType<<std::endl;
             return;
         }
     }else if(targetColType == "double"){
         if(!isDouble(valueToChange)){
             std::cout<<"Invalid new update value. It should be:"<<targetColType<<std::endl;
             return;
         }
     }
     for(int i=0;i<this->getRows().size();i++){
         std::string row = this->getRows()[i];
         std::vector<std::string> tokens = this->splitLineByDelimeter(',',row);
         std::string valToCheck = tokens.at(searchCol-1);
         if((valToCheck == "NULL" && searchVal != "NULL")
            ||  (valToCheck != "NULL" && searchVal == "NULL")){
             newTableRows.push_back(row);
             continue;
         }
         if(valToCheck == "NULL" && searchVal == "NULL"){
             std::string newRow = "";
             for(int i=0;i<tokens.size()-1;i++){
                 newRow += tokens.at(i)+",";
             }
             newRow += tokens.at(tokens.size()-1);
             newTableRows.push_back(newRow);
             continue;
         }
         if(type == "int"){
             int toCheck = std::stoi(valToCheck);
             int valueChecked = std::stoi(searchVal);
             if(toCheck==valueChecked){
                 tokens.at(targetCol-1) = valueToChange;
             }
             std::string newRow = "";
             for(int i=0;i<tokens.size()-1;i++){
                 newRow += tokens.at(i)+",";
             }
             newRow += tokens.at(tokens.size()-1);
             newTableRows.push_back(newRow);
         }
         else if(type=="string"){
             if(searchVal == valToCheck){
                 tokens.at(targetCol-1) = valueToChange;
             }
             std::string newRow = "";
             for(int i=0;i<tokens.size()-1;i++){
                 newRow += tokens.at(i)+",";
             }
             newRow += tokens.at(tokens.size()-1);
             newTableRows.push_back(newRow);
         }
         else if(type=="double"){
             double toCheck = std::stod(valToCheck);
             double valueChecked = std::stod(searchVal);
             if(toCheck==valueChecked){
                 tokens.at(targetCol-1) = valueToChange;
             }
             std::string newRow = "";
             for(int i=0;i<tokens.size()-1;i++){
                 newRow += tokens.at(i)+",";
             }
             newRow += tokens.at(tokens.size()-1);
             newTableRows.push_back(newRow);
         }
     }
     this->setRows(newTableRows);
     std::cout<<"Successfully updated value!"<<std::endl;
 }
References getRows(), getTypes(), isDouble(), isInteger(), setRows(), splitLineByDelimeter(), and string.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Table & object) friend
Definition at line 103 of file Table.cpp.
{
     out<<table.getTableName()+',';
     for(int i=0;i<table.getTypes().size()-1;i++){
         out<<table.getTypes()[i]+',';
     }
     out<<table.getTypes()[table.getTypes().size()-1]<<std::endl;
     for(int i=0;i<table.getColNames().size()-1;i++){
         out<<table.getColNames()[i]+',';
     }
     out<<table.getColNames()[table.getColNames().size()-1]<<std::endl;
     for(int i=0;i<table.getRows().size();i++){
         out<<table.getRows()[i]<<std::endl;
     }
     return out;
 }
operator>>
std::istream& operator>> (std::istream & in, Table & object) friend
Member Data Documentation
colNames
std::vector<std::string> Table::colNames private
Definition at line 22 of file Table.h.
pathToFile
std::string Table::pathToFile private
Definition at line 18 of file Table.h.
rows
std::vector<std::string> Table::rows private
Definition at line 21 of file Table.h.
tableName
std::string Table::tableName private
Definition at line 19 of file Table.h.
types
std::vector<std::string> Table::types private
Definition at line 20 of file Table.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Database/headers/Table.h
C:/Users/Moni/CLionProjects/Database/sources/Table.cpp